"""
Presets & Historical Scenarios for Pax Historia (Flagship 2026 + Complete Historical Catalog)
"""
from typing import Dict, List, Any

PRESETS: Dict[str, Dict[str, Any]] = {
    "modern_2026": {
        "id": "modern_2026",
        "name_ru": "2026: Рассвет ИИ и Многополярный кризис",
        "name_en": "2026: Dawn of AI & Multipolar Crisis",
        "start_year": 2026,
        "start_month": 1,
        "start_day": 1,
        "era": "Digital, Quantum & AI Super-Era 2026",
        "description_ru": "2026 год. Гонка автономных военных систем и квантового ИИ, передел глобальных торговых путей, глушение спутников и интернета, расширение БРИКС+ и противостояние блоков определяют будущее планеты.",
        "description_en": "2026. The military AI arms race, electronic warfare & satellite jamming, BRICS+ expansion, microchip battles, and high tensions between superpowers.",
        "initial_events": [
            {
                "title_ru": "Глобальный стратегический баланс 2026 года",
                "title_en": "Global Strategic Equilibrium 2026",
                "text_ru": "1 января 2026 года. Мир вступил в эру сетецентрических войн, тотального РЭБ, глушения коммуникаций и искусственного интеллекта. Выберите курс вашей державы.",
                "text_en": "January 1, 2026. Humanity enters the era of network-centric warfare, cognitive operations, electronic jamming, and autonomous AI."
            }
        ],
        "nations": {
            "russia": {
                "id": "russia",
                "name_ru": "Российская Федерация",
                "name_en": "Russian Federation",
                "leader": "Владимир Путин",
                "ideology": "Суверенный Консерватизм / Многополярность",
                "regime_type": "Президентская Республика",
                "capital": "Москва",
                "flag_emoji": "🇷🇺",
                "color": "#0284C7",
                "stability": 82.0,
                "war_support": 85.0,
                "political_power": 380.0,
                "corruption_index": 28.0,
                "ruling_party": "Единая Россия / Патриотический фронт",
                "approval_rating": 81.0,
                "martial_law": False,
                "gdp_billions": 2450.0,
                "gdp_growth": 3.6,
                "treasury_billions": 680.0,
                "debt_percent_gdp": 16.5,
                "inflation_percent": 5.2,
                "tax_rate_corporate": 25.0,
                "tax_rate_income": 15.0,
                "tariff_rate": 8.0,
                "gold_reserves_tons": 2350.0,
                "population_millions": 146.5,
                "manpower_thousands": 3200.0,
                "unemployment_rate": 2.8,
                "quality_of_life": 77.0,
                "literacy_percent": 99.8,
                "internet_status": "ONLINE",
                "internet_freedom": 62.0,
                "gps_jamming_active": True,
                "satellite_recon_active": True,
                "cyber_defense_level": 9,
                "cyber_offense_level": 9,
                "ai_supremacy_index": 78.0,
                "deep_packet_inspection": True,
                "resources": {
                    "oil_mbd": 10.8,
                    "natural_gas_bcm": 640.0,
                    "rare_earths_ktons": 85.0,
                    "uranium_tons": 3200.0,
                    "steel_mtons": 72.0,
                    "semiconductors_index": 65,
                    "grain_mtons": 145.0,
                    "energy_grid_gw": 250.0
                },
                "army_divisions": 115,
                "armored_brigades": 60,
                "drone_swarms": 120,
                "navy_ships": 240,
                "aircraft_carriers": 1,
                "submarines": 62,
                "air_wings": 135,
                "stealth_jets": 45,
                "hypersonic_missiles": 180,
                "air_defense_batteries": 110,
                "nuclear_warheads": 5580,
                "military_doctrine": "Глубокая РЭБ-дезинтеграция и гиперзвуковое сдерживание",
                "research_points": 380.0,
                "tech_era": "Digital, Quantum & AI Super-Era 2026",
                "unlocked_techs": [
                    "drone_tactics", "5g_network", "quantum_cryptography_basics",
                    "hypersonic_glide", "advanced_anti_air", "satellite_jamming_suite",
                    "ai_fire_control", "arctic_resource_drilling"
                ],
                "current_research": "autonomous_ai_battlefield",
                "provinces": ["Москва", "Санкт-Петербург", "Урал", "Сибирь", "Дальний Восток", "Крым", "Донбасс", "Арктическая зона"],
                "controlled_straits": ["Керченский пролив", "Северный морской путь"],
                "allies": ["belarus", "csto", "brics_bloc"],
                "non_aggression": ["china", "india", "iran", "saudi_arabia"],
                "at_war": ["ukraine"],
                "puppets": ["belarus"],
                "guarantees": ["armenia", "syria", "kazakhstan"],
                "embargoes": ["usa", "uk", "eu"],
                "relations": {"china": 85, "india": 75, "iran": 80, "belarus": 95, "usa": -85, "eu": -80, "ukraine": -95},
                "spy_networks": {"ukraine": 85, "usa": 70, "eu": 75, "uk": 65},
                "covert_ops_active": []
            },
            "usa": {
                "id": "usa",
                "name_ru": "Соединенные Штаты Америки",
                "name_en": "United States of America",
                "leader": "Президент США",
                "ideology": "Либеральная Демократия / Атлантизм",
                "regime_type": "Федеративная Республика",
                "capital": "Вашингтон",
                "flag_emoji": "🇺🇸",
                "color": "#1D4ED8",
                "stability": 68.0,
                "war_support": 58.0,
                "political_power": 350.0,
                "corruption_index": 20.0,
                "ruling_party": "Двухпартийная система",
                "approval_rating": 48.0,
                "martial_law": False,
                "gdp_billions": 28500.0,
                "gdp_growth": 2.2,
                "treasury_billions": 950.0,
                "debt_percent_gdp": 124.0,
                "inflation_percent": 3.1,
                "tax_rate_corporate": 21.0,
                "tax_rate_income": 30.0,
                "tariff_rate": 15.0,
                "gold_reserves_tons": 8133.0,
                "population_millions": 340.0,
                "manpower_thousands": 2400.0,
                "unemployment_rate": 4.1,
                "quality_of_life": 86.0,
                "literacy_percent": 99.0,
                "internet_status": "ONLINE",
                "internet_freedom": 82.0,
                "gps_jamming_active": False,
                "satellite_recon_active": True,
                "cyber_defense_level": 9,
                "cyber_offense_level": 9,
                "ai_supremacy_index": 92.0,
                "deep_packet_inspection": False,
                "resources": {
                    "oil_mbd": 13.2,
                    "natural_gas_bcm": 980.0,
                    "rare_earths_ktons": 42.0,
                    "uranium_tons": 1100.0,
                    "steel_mtons": 80.0,
                    "semiconductors_index": 90,
                    "grain_mtons": 380.0,
                    "energy_grid_gw": 1200.0
                },
                "army_divisions": 75,
                "armored_brigades": 40,
                "drone_swarms": 95,
                "navy_ships": 295,
                "aircraft_carriers": 11,
                "submarines": 68,
                "air_wings": 190,
                "stealth_jets": 240,
                "hypersonic_missiles": 40,
                "air_defense_batteries": 95,
                "nuclear_warheads": 5044,
                "military_doctrine": "Глобальное превосходство и ударные АУГ",
                "research_points": 550.0,
                "tech_era": "Digital, Quantum & AI Super-Era 2026",
                "unlocked_techs": [
                    "drone_tactics", "5g_network", "quantum_cryptography_basics",
                    "advanced_anti_air", "ai_fire_control", "stealth_generation_6"
                ],
                "current_research": "orbital_kinetic_strike",
                "provinces": ["Вашингтон", "Калифорния", "Техас", "Нью-Йорк", "Флорида", "Аляска", "Гавайи"],
                "controlled_straits": ["Панамский канал"],
                "allies": ["nato", "uk", "eu", "japan", "south_korea", "israel", "taiwan"],
                "non_aggression": [],
                "at_war": [],
                "puppets": [],
                "guarantees": ["taiwan", "ukraine", "israel", "philippines"],
                "embargoes": ["russia", "iran", "north_korea"],
                "relations": {"uk": 90, "eu": 85, "japan": 90, "taiwan": 90, "china": -60, "russia": -85},
                "spy_networks": {"russia": 80, "china": 80, "iran": 85},
                "covert_ops_active": []
            },
            "china": {
                "id": "china",
                "name_ru": "Китайская Народная Республика",
                "name_en": "People's Republic of China",
                "leader": "Си Цзиньпин",
                "ideology": "Социализм с китайской спецификой",
                "regime_type": "Социалистическая Республика",
                "capital": "Пекин",
                "flag_emoji": "🇨🇳",
                "color": "#DC2626",
                "stability": 88.0,
                "war_support": 84.0,
                "political_power": 420.0,
                "corruption_index": 22.0,
                "ruling_party": "Коммунистическая партия Китая",
                "approval_rating": 89.0,
                "martial_law": False,
                "gdp_billions": 19800.0,
                "gdp_growth": 4.8,
                "treasury_billions": 3400.0,
                "debt_percent_gdp": 55.0,
                "inflation_percent": 1.8,
                "tax_rate_corporate": 25.0,
                "tax_rate_income": 20.0,
                "tariff_rate": 6.0,
                "gold_reserves_tons": 2260.0,
                "population_millions": 1410.0,
                "manpower_thousands": 5500.0,
                "unemployment_rate": 5.0,
                "quality_of_life": 80.0,
                "literacy_percent": 99.5,
                "internet_status": "ONLINE",
                "internet_freedom": 40.0,
                "gps_jamming_active": False,
                "satellite_recon_active": True,
                "cyber_defense_level": 9,
                "cyber_offense_level": 9,
                "ai_supremacy_index": 89.0,
                "deep_packet_inspection": True,
                "resources": {
                    "oil_mbd": 4.2,
                    "natural_gas_bcm": 230.0,
                    "rare_earths_ktons": 210.0,
                    "uranium_tons": 2800.0,
                    "steel_mtons": 980.0,
                    "semiconductors_index": 85,
                    "grain_mtons": 680.0,
                    "energy_grid_gw": 2900.0
                },
                "army_divisions": 130,
                "armored_brigades": 70,
                "drone_swarms": 150,
                "navy_ships": 380,
                "aircraft_carriers": 3,
                "submarines": 75,
                "air_wings": 175,
                "stealth_jets": 140,
                "hypersonic_missiles": 220,
                "air_defense_batteries": 125,
                "nuclear_warheads": 600,
                "military_doctrine": "Интегрированная ракетно-дронная блокада и A2/AD",
                "research_points": 520.0,
                "tech_era": "Digital, Quantum & AI Super-Era 2026",
                "unlocked_techs": [
                    "drone_tactics", "5g_network", "quantum_cryptography_basics",
                    "hypersonic_glide", "advanced_anti_air"
                ],
                "current_research": "6g_terahertz_radar",
                "provinces": ["Пекин", "Шанхай", "Шэньчжэнь", "Гуандун", "Сычуань", "Синьцзян", "Тибет", "Гонконг"],
                "controlled_straits": ["Тайваньский пролив"],
                "allies": ["north_korea", "pakistan", "brics_bloc", "sco"],
                "non_aggression": ["russia", "iran"],
                "at_war": [],
                "puppets": [],
                "guarantees": ["pakistan", "north_korea"],
                "embargoes": [],
                "relations": {"russia": 85, "pakistan": 90, "north_korea": 80, "usa": -60},
                "spy_networks": {"taiwan": 90, "usa": 80},
                "covert_ops_active": []
            }
        }
    },
    "ww2_1936": {
        "id": "ww2_1936",
        "name_ru": "1936: Надвигающаяся буря (Вторая мировая)",
        "name_en": "1936: The Gathering Storm (World War II)",
        "start_year": 1936,
        "start_month": 1,
        "start_day": 1,
        "era": "Industrial & Atomic Era",
        "description_ru": "Великие державы готовятся к решающему столкновению идеологий в Европе и Азии.",
        "description_en": "Great powers prepare for the decisive clash of ideologies across Europe and Asia.",
        "initial_events": [{"title_ru": "Мир перед войной", "title_en": "World before War", "text_ru": "1936 год. Ремилитаризация Рейнской области.", "text_en": "1936. Remilitarization of the Rhineland."}],
        "nations": {
            "ussr": {"id": "ussr", "name_ru": "СССР", "name_en": "USSR", "leader": "Иосиф Сталин", "ideology": "Коммунизм", "capital": "Москва", "flag_emoji": "🚩", "color": "#DC2626", "stability": 80, "war_support": 75, "political_power": 300, "gdp_billions": 380, "treasury_billions": 45, "manpower_thousands": 4500, "army_divisions": 140, "drone_swarms": 0, "navy_ships": 65, "air_wings": 45, "nuclear_warheads": 0, "internet_status": "OFFLINE_ERA", "gps_jamming_active": False, "provinces": ["Москва", "Ленинград", "Киев", "Урал"], "allies": [], "at_war": [], "relations": {}},
            "germany": {"id": "germany", "name_ru": "Германский Рейх", "name_en": "German Reich", "leader": "Адольф Гитлер", "ideology": "Фашизм", "capital": "Берлин", "flag_emoji": "🦅", "color": "#4B5563", "stability": 85, "war_support": 90, "political_power": 320, "gdp_billions": 420, "treasury_billions": 35, "manpower_thousands": 3200, "army_divisions": 80, "drone_swarms": 0, "navy_ships": 40, "air_wings": 60, "nuclear_warheads": 0, "internet_status": "OFFLINE_ERA", "gps_jamming_active": False, "provinces": ["Берлин", "Бавария", "Рейнланд"], "allies": [], "at_war": [], "relations": {}}
        }
    },
    "ww1_1914": {
        "id": "ww1_1914",
        "name_ru": "1914: Великая война (Первая мировая)",
        "name_en": "1914: The Great War (World War I)",
        "start_year": 1914,
        "start_month": 6,
        "start_day": 28,
        "era": "Industrial Trench Era",
        "description_ru": "Убийство эрцгерцога в Сараево поджигает фитиль глобального конфликта империй.",
        "description_en": "Assassination in Sarajevo sparks global clash of empires.",
        "initial_events": [{"title_ru": "Сараевский кризис", "title_en": "Sarajevo Crisis", "text_ru": "Австро-Венгрия объявляет войну Сербии.", "text_en": "Austria-Hungary mobilizes."}],
        "nations": {
            "russian_empire": {"id": "russian_empire", "name_ru": "Российская Империя", "name_en": "Russian Empire", "leader": "Николай II", "ideology": "Монархия", "capital": "Петроград", "flag_emoji": "👑", "color": "#1E3A8A", "stability": 70, "war_support": 80, "political_power": 250, "gdp_billions": 310, "treasury_billions": 65, "manpower_thousands": 5500, "army_divisions": 120, "drone_swarms": 0, "navy_ships": 70, "air_wings": 15, "nuclear_warheads": 0, "internet_status": "OFFLINE_ERA", "gps_jamming_active": False, "provinces": ["Петроград", "Москва", "Варшава"], "allies": [], "at_war": [], "relations": {}}
        }
    },
    "coldwar_1962": {
        "id": "coldwar_1962",
        "name_ru": "1962: Карибский кризис",
        "name_en": "1962: Cuban Missile Crisis",
        "start_year": 1962,
        "start_month": 10,
        "start_day": 14,
        "era": "Nuclear & Space Era",
        "description_ru": "СССР и США на грани ракетно-ядерной войны.",
        "description_en": "Superpowers on the brink of thermonuclear war.",
        "initial_events": [{"title_ru": "Ракеты на Кубе", "title_en": "Missiles in Cuba", "text_ru": "Развертывание баллистических ракет на Кубе.", "text_en": "Missile deployment in Cuba."}],
        "nations": {
            "ussr": {"id": "ussr", "name_ru": "СССР", "name_en": "USSR", "leader": "Никита Хрущёв", "ideology": "Социализм", "capital": "Москва", "flag_emoji": "🚩", "color": "#DC2626", "stability": 80, "war_support": 85, "political_power": 310, "gdp_billions": 1600, "treasury_billions": 180, "manpower_thousands": 5000, "army_divisions": 160, "drone_swarms": 0, "navy_ships": 280, "air_wings": 140, "nuclear_warheads": 3300, "internet_status": "OFFLINE_ERA", "gps_jamming_active": False, "provinces": ["Москва", "Ленинград", "Киев"], "allies": [], "at_war": [], "relations": {}}
        }
    },
    "after_the_end_2666": {
        "id": "after_the_end_2666",
        "name_ru": "2666: После Конца (Постапокалипсис)",
        "name_en": "2666: After the End",
        "start_year": 2666,
        "start_month": 7,
        "start_day": 4,
        "era": "Neo-Feudal Post-Collapse Era",
        "description_ru": "Нео-феодальные королевства борются за древние технологии на руинах цивилизации.",
        "description_en": "Neo-feudal realms vie for lost tech on ruins of the old world.",
        "initial_events": [{"title_ru": "Новый Темный Век", "title_en": "New Dark Age", "text_ru": "Восстание из пепла древней Америки.", "text_en": "Rising from the ashes."}],
        "nations": {
            "holy_colombian": {"id": "holy_colombian", "name_ru": "Священная Колумбия", "name_en": "Holy Colombia", "leader": "Леонтий III", "ideology": "Нео-Феодализм", "capital": "Атланта", "flag_emoji": "⚜️", "color": "#7C3AED", "stability": 75, "war_support": 70, "political_power": 220, "gdp_billions": 45, "treasury_billions": 8, "manpower_thousands": 250, "army_divisions": 28, "drone_swarms": 0, "navy_ships": 22, "air_wings": 0, "nuclear_warheads": 0, "internet_status": "OFFLINE_ERA", "gps_jamming_active": False, "provinces": ["Атланта", "Джорджия"], "allies": [], "at_war": [], "relations": {}}
        }
    },
    "iron_peace_1920": {
        "id": "iron_peace_1920",
        "name_ru": "1920: Железный мир (Империя выжила)",
        "name_en": "1920: The Iron Peace",
        "start_year": 1920,
        "start_month": 5,
        "start_day": 1,
        "era": "Alternate Belle Époque",
        "description_ru": "Российская Империя выжила благодаря реформам Столыпина.",
        "description_en": "Russian Empire survived through constitutional reforms.",
        "initial_events": [{"title_ru": "Мирный манифест", "title_en": "Peace Manifesto", "text_ru": "Золотой век реформ.", "text_en": "Golden era of growth."}],
        "nations": {
            "russian_empire": {"id": "russian_empire", "name_ru": "Всероссийская Империя", "name_en": "All-Russian Empire", "leader": "Михаил II", "ideology": "Монархия", "capital": "Петроград", "flag_emoji": "👑", "color": "#1D4ED8", "stability": 85, "war_support": 60, "political_power": 280, "gdp_billions": 520, "treasury_billions": 95, "manpower_thousands": 6000, "army_divisions": 110, "drone_swarms": 0, "navy_ships": 90, "air_wings": 30, "nuclear_warheads": 0, "internet_status": "OFFLINE_ERA", "gps_jamming_active": False, "provinces": ["Петроград", "Москва", "Киев"], "allies": [], "at_war": [], "relations": {}}
        }
    }
}

def get_all_presets() -> List[Dict[str, Any]]:
    return list(PRESETS.values())

def get_preset_by_id(preset_id: str) -> Dict[str, Any]:
    return PRESETS.get(preset_id, PRESETS["modern_2026"])
